### ISSUE TITLE
Q: Installation

### ISSUE THREAD

**Issue by osmalpkoras** [lingchensanwen/DCQA-QUD-parsing#1]
Hello,

I failed to install this repository on my Apple MacBook Pro (Chip: Apple M1 Pro) following the ReadMe. Upon investigation, I noticed that the transformer library included in this repository is rather old (3.1.0 from 2020) requiring me to compile some dependencies for my machine with an older Rust Compiler. I could not figure it which version I needed.

Q: Can you provide guidance on how to install this library on the above machine? Or can you provide more information on the dependencies? Is it possible to upgrade the transformer version? Which Rust Compiler version do I need?

Thank you in advance!

**Comment by lingchensanwen** [comment]
Hi, as we discussed in the email, refer to this colab notebook can help set up: https://colab.research.google.com/drive/1qzB-sIuqNIarQjVVg41BrNyCfAd1LdsZ?usp=sharing
